# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yummy Theme
name: DONGChuan
email: dongchuan55@gmail.com
location: Nice, France
company: MyCompany
company_url: https://github.com/DONGChuan
github_url: https://github.com/DONGChuan

url: "http://yourdomain.com" # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /about
    label: About

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'
